source "https://rubygems.org"

gem "devise_token_auth"
gem "devise"
gem "graphql_devise"
gem "graphql"
gem "puma", ">= 5.0"
gem "rails", "~> 7.1.4"
gem "sqlite3", ">= 1.4"
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "brakeman", require: false
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rubocop-rails-omakase", require: false
end
